# Project information
site_name: Ciro's Website
site_author: Ciro Bermudez
site_description: >-
  This is my personal website, where I share my projects and ideas.
  
# Copyright
copyright: >-
  Copyright &copy; 2025 Ciro Bermudez

# Repository
repo_name: cirofabianbermudez
repo_url: https://github.com/cirofabianbermudez
# site_url: https://cirofabianbermudez.com
  
theme:
  name: material
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navidation.expand
    - header.autohide
    - content.code.copy
  font:
    text: Inter
    code: Monaco
  logo: assets/images/site_logo/logo.svg
  favicon: assets/images/site_logo/favicon.svg

# Plugins
plugins:
  - search

# Additional configuration
extra:
  generator: false
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/ciro-fabian-bermudez-marquez-a93096227
  - icon: fontawesome/brands/github
    link: https://github.com/cirofabianbermudez

# Custom stylesheets
extra_css:
  - stylesheets/extra.css

# Custom javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
  - About me:
    - about_me/index.md
